EProjectGroup2/Controllers/EducationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EProjectGroup2.DataContext;
using EProjectGroup2.Models;

namespace EProjectGroup2.Controllers
{
    public class EducationsController : Controller
    {
        private readonly ClinicManagementDataContext _context;

        public EducationsController(ClinicManagementDataContext context)
        {
            _context = context;
        }

        // GET: Educations
        public async Task<IActionResult> Index()
        {
            var clinicManagementDataContext = _context.Educations.Include(e => e.Users);
            return View(await clinicManagementDataContext.ToListAsync());
        }

        // GET: Educations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Educations == null)
            {
                return NotFound();
            }

            var educations = await _context.Educations
                .Include(e => e.Users)
                .FirstOrDefaultAsync(m => m.EducationID == id);
            if (educations == null)
            {
                return NotFound();
            }

            return View(educations);
        }

        // GET: Educations/Create
        public IActionResult Create()
        {
            ViewData["UserID"] = new SelectList(_context.Users, "UserID", "UserID");
            return View();
        }

        // POST: Educations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EducationID,EducationName,EducationDescription,EducationType,EducationContent,EducationDate,UserID")] Educations educations)
        {
            if (ModelState.IsValid)
            {
                _context.Add(educations);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserID"] = new SelectList(_context.Users, "UserID", "UserID", educations.UserID);
            return View(educations);
        }

        // GET: Educations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Educations == null)
            {
                return NotFound();
            }

            var educations = await _context.Educations.FindAsync(id);
            if (educations == null)
            {
                return NotFound();
            }
            ViewData["UserID"] = new SelectList(_context.Users, "UserID", "UserID", educations.UserID);
            return View(educations);
        }

        // POST: Educations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EducationID,EducationName,EducationDescription,EducationType,EducationContent,EducationDate,UserID")] Educations educations)
        {
            if (id != educations.EducationID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(educations);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EducationsExists(educations.EducationID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserID"] = new SelectList(_context.Users, "UserID", "UserID", educations.UserID);
            return View(educations);
        }

        // GET: Educations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Educations == null)
            {
                return NotFound();
            }

            var educations = await _context.Educations
                .Include(e => e.Users)
                .FirstOrDefaultAsync(m => m.EducationID == id);
            if (educations == null)
            {
                return NotFound();
            }

            return View(educations);
        }

        // POST: Educations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Educations == null)
            {
                return Problem("Entity set 'ClinicManagementDataContext.Educations'  is null.");
            }
            var educations = await _context.Educations.FindAsync(id);
            if (educations != null)
            {
                _context.Educations.Remove(educations);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EducationsExists(int id)
        {
          return (_context.Educations?.Any(e => e.EducationID == id)).GetValueOrDefault();
        }
    }
}

EProjectGroup2/Controllers/FeedbacksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EProjectGroup2.DataContext;
using EProjectGroup2.Models;

namespace EProjectGroup2.Controllers
{
    public class FeedbacksController : Controller
    {
        private readonly ClinicManagementDataContext _context;

        public FeedbacksController(ClinicManagementDataContext context)
        {
            _context = context;
        }

        // GET: Feedbacks
        public async Task<IActionResult> Index()
        {
            var clinicManagementDataContext = _context.Feedbacks.Include(f => f.Products);
            return View(await clinicManagementDataContext.ToListAsync());
        }

        // GET: Feedbacks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Feedbacks == null)
            {
                return NotFound();
            }

            var feedbacks = await _context.Feedbacks
                .Include(f => f.Products)
                .FirstOrDefaultAsync(m => m.FeedbackID == id);
            if (feedbacks == null)
            {
                return NotFound();
            }

            return View(feedbacks);
        }

        // GET: Feedbacks/Create
        public IActionResult Create()
        {
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID");
            return View();
        }

        // POST: Feedbacks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FeedbackID,FeedbackName,Description,ProductID")] Feedbacks feedbacks)
        {
            if (ModelState.IsValid)
            {
                _context.Add(feedbacks);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID", feedbacks.ProductID);
            return View(feedbacks);
        }

        // GET: Feedbacks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Feedbacks == null)
            {
                return NotFound();
            }

            var feedbacks = await _context.Feedbacks.FindAsync(id);
            if (feedbacks == null)
            {
                return NotFound();
            }
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID", feedbacks.ProductID);
            return View(feedbacks);
        }

        // POST: Feedbacks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FeedbackID,FeedbackName,Description,ProductID")] Feedbacks feedbacks)
        {
            if (id != feedbacks.FeedbackID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(feedbacks);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeedbacksExists(feedbacks.FeedbackID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID", feedbacks.ProductID);
            return View(feedbacks);
        }

        // GET: Feedbacks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Feedbacks == null)
            {
                return NotFound();
            }

            var feedbacks = await _context.Feedbacks
                .Include(f => f.Products)
                .FirstOrDefaultAsync(m => m.FeedbackID == id);
            if (feedbacks == null)
            {
                return NotFound();
            }

            return View(feedbacks);
        }

        // POST: Feedbacks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Feedbacks == null)
            {
                return Problem("Entity set 'ClinicManagementDataContext.Feedbacks'  is null.");
            }
            var feedbacks = await _context.Feedbacks.FindAsync(id);
            if (feedbacks != null)
            {
                _context.Feedbacks.Remove(feedbacks);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FeedbacksExists(int id)
        {
          return (_context.Feedbacks?.Any(e => e.FeedbackID == id)).GetValueOrDefault();
        }
    }
}

EProjectGroup2/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EProjectGroup2.DataContext;
using EProjectGroup2.Models;

namespace EProjectGroup2.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ClinicManagementDataContext _context;

        public OrdersController(ClinicManagementDataContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index(int? orderId)
        {
            var orders = _context.Orders.Include(o => o.OrderDetails).ThenInclude(od => od.Products).ToList();

            if (orderId != null)
            {
                orders = orders.Where(o => o.OrderID == orderId).ToList();
            }

            return View(orders);
        }


        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders
                .Include(o => o.Address)
                .Include(o => o.Customers)
                .Include(o => o.Users)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["AddressID"] = new SelectList(_context.Address, "AddressID", "AddressID");
            ViewData["CustomerID"] = new SelectList(_context.Customers, "CustomerID", "CustomerID");
            ViewData["UserID"] = new SelectList(_context.Users, "UserID", "UserID");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderID,Message,CreatedDate,Status,AddressID,CustomerID,UserID")] Orders orders)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orders);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AddressID"] = new SelectList(_context.Address, "AddressID", "AddressID", orders.AddressID);
            ViewData["CustomerID"] = new SelectList(_context.Customers, "CustomerID", "CustomerID", orders.CustomerID);
            ViewData["UserID"] = new SelectList(_context.Users, "UserID", "UserID", orders.UserID);
            return View(orders);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders.FindAsync(id);
            if (orders == null)
            {
                return NotFound();
            }
            ViewData["AddressID"] = new SelectList(_context.Address, "AddressID", "AddressID", orders.AddressID);
            ViewData["CustomerID"] = new SelectList(_context.Customers, "CustomerID", "CustomerID", orders.CustomerID);
            ViewData["UserID"] = new SelectList(_context.Users, "UserID", "UserID", orders.UserID);
            return View(orders);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderID,Message,CreatedDate,Status,AddressID,CustomerID,UserID")] Orders orders)
        {
            if (id != orders.OrderID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orders);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrdersExists(orders.OrderID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AddressID"] = new SelectList(_context.Address, "AddressID", "AddressID", orders.AddressID);
            ViewData["CustomerID"] = new SelectList(_context.Customers, "CustomerID", "CustomerID", orders.CustomerID);
            ViewData["UserID"] = new SelectList(_context.Users, "UserID", "UserID", orders.UserID);
            return View(orders);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var orders = await _context.Orders
                .Include(o => o.Address)
                .Include(o => o.Customers)
                .Include(o => o.Users)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'ClinicManagementDataContext.Orders'  is null.");
            }
            var orders = await _context.Orders.FindAsync(id);
            if (orders != null)
            {
                _context.Orders.Remove(orders);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrdersExists(int id)
        {
          return (_context.Orders?.Any(e => e.OrderID == id)).GetValueOrDefault();
        }
    }
}

EProjectGroup2/Views/Admin/Educations.cshtml
@model IEnumerable<EProjectGroup2.Models.Educations>

@{
    ViewData["Title"] = "Educations";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Educations</h1>

<p>
    <a asp-controller="Feedbacks" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EducationName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EducationDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EducationType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EducationContent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EducationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Users)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EducationName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EducationDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EducationType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EducationContent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EducationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Users.UserName)
            </td>
            <td>
                    <a asp-controller="Educations" asp-action="Edit" asp-route-id="@item.EducationID">Edit</a> |
                    <a asp-controller="Educations" asp-action="Details" asp-route-id="@item.EducationID">Details</a> |
                    <a asp-controller="Educations" asp-action="Delete" asp-route-id="@item.EducationID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

EProjectGroup2/Views/Admin/FeedBacks.cshtml
@model IEnumerable<EProjectGroup2.Models.Feedbacks>

@{
    ViewData["Title"] = "FeedBacks";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>FeedBacks</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FeedbackName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Products)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FeedbackName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Products.ProductName)
            </td>
            <td>
                    <a asp-controller="Feedbacks" asp-action="Edit" asp-route-id="@item.FeedbackID">Edit</a> |
                    <a asp-controller="Feedbacks" asp-action="Details" asp-route-id="@item.FeedbackID">Details</a> |
                    <a asp-controller="Feedbacks" asp-action="Delete" asp-route-id="@item.FeedbackID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

EProjectGroup2/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1 style="margin-top:64px">Index</h1>

EProjectGroup2/Views/Admin/Orders.cshtml
@model IEnumerable<EProjectGroup2.Models.Orders>

@{
    ViewData["Title"] = "Orders";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Orders</h1>

<p>
    <a asp-controller="Orders" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Message)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customers)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Users)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Message)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address.AddressName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customers.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Users.UserName)
            </td>
            <td>
                    <a asp-controller="Orders" asp-action="Edit" asp-route-id="@item.OrderID">Edit</a> |
                    <a asp-controller="Orders" asp-action="Details" asp-route-id="@item.OrderID">Details</a> |
                    <a asp-controller="Orders" asp-action="Delete" asp-route-id="@item.OrderID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

EProjectGroup2/Views/Admin/Products.cshtml
@model IEnumerable<EProjectGroup2.Models.Products>

@{
    ViewData["Title"] = "Products";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Products</h1>

<p>
    <a asp-controller="Products" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImportDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpireDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ManufacturedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Manufacturer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categories)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductTypes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImagePath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImportDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpireDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ManufacturedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Manufacturer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categories.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductTypes.ProductName)
            </td>
            <td>
                <a asp-controller="Products" asp-action="Edit" asp-route-id="@item.ProductID">Edit</a> |
                
                <a asp-controller="Products" asp-action="Delete" asp-route-id="@item.ProductID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

EProjectGroup2/Views/Admin/Users.cshtml
@model IEnumerable<EProjectGroup2.Models.Users>

@{
    ViewData["Title"] = "Users";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Users</h1>

<p>
    <a asp-controller="Users" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                    <a asp-controller="Users" asp-action="Edit" asp-route-id="@item.UserID">Edit</a> |
                    <a asp-controller="Users" asp-action="Details" asp-route-id="@item.UserID">Details</a> |
                    <a asp-controller="Users" asp-action="Delete" asp-route-id="@item.UserID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>