EProjectGroup2/Models/OrderDetails.cs
using System.ComponentModel.DataAnnotations;

namespace EProjectGroup2.Models
{
    public class OrderDetails
    {
        public int? Quantity { get; set; }
        public float? Discount { get; set; }

        public int ProductID { get; set; }
        public Products? Products { get; set; }
        public int OrderID { get; set; }
        public Orders? Orders { get; set; }
    }
}

EProjectGroup2/Controllers/OrderDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EProjectGroup2.DataContext;
using EProjectGroup2.Models;

namespace EProjectGroup2.Controllers
{
    public class OrderDetailsController : Controller
    {
        private readonly ClinicManagementDataContext _context;

        public OrderDetailsController(ClinicManagementDataContext context)
        {
            _context = context;
        }

        // GET: OrderDetails
        public async Task<IActionResult> Index()
        {
            var cart = GetOrCreateCartForCurrentCustomer();

            var orderDetails = await _context.OrderDetails
                .Include(o => o.Orders)
                .Include(o => o.Products)
                .Where(o => o.Orders.CustomerID == cart.CustomerID)
                .OrderByDescending(o => o.OrderID)
                .ToListAsync();

            var groupedOrderDetails = orderDetails.GroupBy(o => o.OrderID).ToList();
            if (groupedOrderDetails == null)
            {
                return RedirectToAction("Index","Home");
            }
            return View(groupedOrderDetails);

        }

        private Orders GetOrCreateCartForCurrentCustomer()
        {
            if (HttpContext.Request.Cookies.TryGetValue("CustomerId", out string customerIdStr) && int.TryParse(customerIdStr, out int customerId))
            {
                var cart = _context.Orders
                    .Include(c => c.OrderDetails)
                    .ThenInclude(cd => cd.Products)
                    .FirstOrDefault(c => c.CustomerID == customerId);

                return cart;
            }

            // CustomerId cookie not found or invalid
            return null;
        }
        [HttpPost]
        public IActionResult CreateOrder(int[] selectedOrders)
        {
            var cart = GetOrCreateCartForCurrentCustomer();
            var address = _context.Address.FirstOrDefault(a => a.AddressID == 1);
            var user = _context.Users.FirstOrDefault(x => x.UserID == 1);
            var orderDetails = new List<OrderDetails>();

            foreach (var orderId in selectedOrders)
            {
                var details = _context.OrderDetails
                    .Include(od => od.Products)
                    .Where(od => od.OrderID == orderId);

                foreach (var detail in details)
                {
                    orderDetails.Add(new OrderDetails
                    {
                        Products = detail.Products,
                        Quantity = detail.Quantity
                    });
                }
            }

            var order = new Orders
            {
                Message = "New order",
                CreatedDate = DateTime.Now,
                Status = false,
                AddressID = address.AddressID,
                CustomerID = cart.CustomerID,
                UserID = user.UserID,
                OrderDetails = orderDetails
            };

            _context.Orders.Add(order);
            _context.SaveChanges();

            return RedirectToAction("Orders", "Home", new { orderId = order.OrderID });
        }




        // GET: OrderDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.OrderDetails == null)
            {
                return NotFound();
            }

            var orderDetails = await _context.OrderDetails
                .Include(o => o.Orders)
                .Include(o => o.Products)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (orderDetails == null)
            {
                return NotFound();
            }

            return View(orderDetails);
        }

        // GET: OrderDetails/Create
        public IActionResult Create()
        {
            ViewData["OrderID"] = new SelectList(_context.Orders, "OrderID", "OrderID");
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID");
            return View();
        }

        // POST: OrderDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Quantity,Discount,ProductID,OrderID")] OrderDetails orderDetails)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orderDetails);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderID"] = new SelectList(_context.Orders, "OrderID", "OrderID", orderDetails.OrderID);
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID", orderDetails.ProductID);
            return View(orderDetails);
        }

        // GET: OrderDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.OrderDetails == null)
            {
                return NotFound();
            }

            var orderDetails = await _context.OrderDetails.FindAsync(id);
            if (orderDetails == null)
            {
                return NotFound();
            }
            ViewData["OrderID"] = new SelectList(_context.Orders, "OrderID", "OrderID", orderDetails.OrderID);
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID", orderDetails.ProductID);
            return View(orderDetails);
        }

        // POST: OrderDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Quantity,Discount,ProductID,OrderID")] OrderDetails orderDetails)
        {
            if (id != orderDetails.OrderID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderDetails);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderDetailsExists(orderDetails.OrderID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderID"] = new SelectList(_context.Orders, "OrderID", "OrderID", orderDetails.OrderID);
            ViewData["ProductID"] = new SelectList(_context.Products, "ProductID", "ProductID", orderDetails.ProductID);
            return View(orderDetails);
        }

        // GET: OrderDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.OrderDetails == null)
            {
                return NotFound();
            }

            var orderDetails = await _context.OrderDetails
                .Include(o => o.Orders)
                .Include(o => o.Products)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (orderDetails == null)
            {
                return NotFound();
            }

            return View(orderDetails);
        }

        // POST: OrderDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.OrderDetails == null)
            {
                return Problem("Entity set 'ClinicManagementDataContext.OrderDetails'  is null.");
            }
            var orderDetails = await _context.OrderDetails.FindAsync(id);
            if (orderDetails != null)
            {
                _context.OrderDetails.Remove(orderDetails);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderDetailsExists(int id)
        {
          return (_context.OrderDetails?.Any(e => e.OrderID == id)).GetValueOrDefault();
        }
    }
}

EProjectGroup2/Views/OrderDetails/Create.cshtml
@model EProjectGroup2.Models.OrderDetails

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Create</h1>

<h4>OrderDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductID" class="control-label"></label>
                <select asp-for="ProductID" class ="form-control" asp-items="ViewBag.ProductID"></select>
            </div>
            <div class="form-group">
                <label asp-for="OrderID" class="control-label"></label>
                <select asp-for="OrderID" class ="form-control" asp-items="ViewBag.OrderID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

EProjectGroup2/Views/OrderDetails/Delete.cshtml
@model EProjectGroup2.Models.OrderDetails

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrderDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Products)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Products.ProductID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Orders)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Orders.OrderID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductID" />
        <input type="hidden" asp-for="OrderID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EProjectGroup2/Views/OrderDetails/Details.cshtml
@model EProjectGroup2.Models.OrderDetails

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Details</h1>

<div>
    <h4>OrderDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Products)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Products.ProductID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Orders)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Orders.OrderID)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

EProjectGroup2/Views/OrderDetails/Edit.cshtml
@model EProjectGroup2.Models.OrderDetails

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Edit</h1>

<h4>OrderDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="ProductID" />
            <input type="hidden" asp-for="OrderID" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EProjectGroup2/Views/OrderDetails/Index.cshtml
@model IEnumerable<System.Linq.IGrouping<int, EProjectGroup2.Models.OrderDetails>>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" action="@Url.Action("CreateOrder", "OrderDetails")">
    <table class="table-auto w-full">
        <thead class="hidden border-b-2 lg:table-header-group">
            <tr>
                <th class="text-left pb-2 font-medium text-[#999]">Select</th>
                <th class="text-left pb-2 font-medium text-[#999]">Product</th>
                <th class="text-left pb-2 font-medium text-[#999]">Quantity</th>
                <th class="text-left pb-2 font-medium text-[#999]">Price</th>
                <th class="text-left pb-2 font-medium text-[#999]">
                    Total Price
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var group in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" name="selectedOrders" value="@group.Key" />
                    </td>
                    <th colspan="4">Order ID: @group.Key</th>
                </tr>
                @foreach (var item in group)
                {
                    <tr class="cursor-pointer hover:bg-[#0000000d] transition-all rounded-lg flex lg:table-row flex-col">
                        <td></td>
                        <td class="py-3">
                            <div class="flex gap-2">
                                <img class="lg:w-[150px] lg:h-[150px] w-[50px] h-[50px] border-2 rounded-lg"
                                     src="./images/hacker.jpg"
                                     alt="" />
                                <span class="font-semibold">@item.Products.ProductName</span>
                            </div>
                        </td>
                        <td class="py-3 align-top">@item.Quantity</td>
                        <td class="py-3 align-top">@item.Products.Price</td>
                        <td class="py-3 align-top">@(item.Quantity * item.Products.Price)</td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <div class="p-3 border-t-2 w-full">
        <div class="text-[20px] mb-3 font-semibold">Total Price: @Model.Sum(group => group.Sum(item => item.Quantity * item.Products.Price))</div>
        <button class="primary-btn h-10 rounded-lg">Checkout</button>
    </div>
</form>

@*<div class="flex flex-col gap-5">
    <table class="table-auto w-full">
        <thead class="hidden border-b-2 lg:table-header-group">
            <tr>
                <th class="text-left pb-2 font-medium text-[#999]">Select</th>
                <th class="text-left pb-2 font-medium text-[#999]">Product</th>
                <th class="text-left pb-2 font-medium text-[#999]">Quantity</th>
                <th class="text-left pb-2 font-medium text-[#999]">Price</th>
                <th class="text-left pb-2 font-medium text-[#999]">
                    Total Price
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var group in Model) {
                @foreach (var item in group)
                {    
                <tr class="cursor-pointer hover:bg-[#0000000d] transition-all rounded-lg flex lg:table-row flex-col">
                        <td>
                            <input type="checkbox" name="selectedOrders" value="@group.Key" />
                        </td>
                    <td class="py-3">
                        <div class="flex gap-2">
                            <img class="lg:w-[150px] lg:h-[150px] w-[50px] h-[50px] border-2 rounded-lg"
                                 src="./images/hacker.jpg"
                                 alt="" />
                            <span class="font-semibold">@item.Products.ProductName</span>
                        </div>
                    </td>
                    <td class="py-3 align-top">@item.Quantity</td>
                    <td class="py-3 align-top">@item.Products.Price</td>
                    <td class="py-3 align-top">@(item.Quantity * item.Products.Price)</td>
                </tr>
                }
            }
        </tbody>
    </table>
    <div class="p-3 border-t-2 w-full">
        <form method="post" action="@Url.Action("CreateOrder", "OrderDetails")">
            <div class="text-[20px] mb-3 font-semibold">Total Price: @Model.Sum(group => group.Sum(item => item.Quantity * item.Products.Price))</div>
            <button class="primary-btn h-10 rounded-lg">Checkout</button>
        </form>
    </div>
</div>*@